<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-12-15T19:15:37 CST" name="Default suite" finished-at="2019-12-15T19:15:38 CST" duration-ms="1088">
    <groups>
    </groups>
    <test started-at="2019-12-15T19:15:37 CST" name="Default test" finished-at="2019-12-15T19:15:38 CST" duration-ms="1088">
      <class name="day63_JavaRecap.Quiz16">
        <test-method signature="Test1()[pri:0, instance:day63_JavaRecap.Quiz16@64c87930]" started-at="2019-12-15T19:15:37 CST" name="Test1" finished-at="2019-12-15T19:15:38 CST" duration-ms="1020" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method day63_JavaRecap.Quiz16.Test1() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method day63_JavaRecap.Quiz16.Test1() didn't finish within the time-out 1000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
      </class> <!-- day63_JavaRecap.Quiz16 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
